### ISSUE TITLE
help for paper and code

### ISSUE THREAD

**Issue by God-bin** [larzw/duke-cassi#1]
I can't find the original  code from Duke . And I also want relative paper about the code. May I get them from you? Thank you.

**Comment by larzw** [comment]
I think they took the website down, which is one reason I created this repo. Here is one of their early papers
https://users.cs.duke.edu/~nikos/reprints/C-024-CASSI-SPIE.pdf
there are a few more by them that may be useful, just look for papers by Wagadarikar and/or Brady. I think the code in this repo reproduces the image in the paper I've linked to (the scene of fruit + the masks). good luck!
